version: '3'
services:
  #Nginx Service
  webserver2:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge


 
